// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exnfyblcxbrwufrpafqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bmZ5YmxjeGJyd3VmcnBhZnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTY3NjYsImV4cCI6MjA2NDY5Mjc2Nn0.eBBQzLG9cDip5rkhJiweo25vn2iRyWvSiyrtn41JQL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);